### ISSUE TITLE
Manuscript: Expanded Discussion on Entity Principle

### ISSUE THREAD

**Issue by berntpopp** [berntpopp/sysndd#75]
**Description:**
Elaborate on the definition and utility of the "entity" concept. Discuss how this principle helps bridge the gap between gene-centric and disease-centric databases and its importance for interoperability.
**Tasks:**
- [ ] Define the "entity" concept in detail.
- [ ] Explain its benefits for database interoperability.
- [ ] Provide examples of how entities facilitate data integration.
